//! Command line interface definition.

use clap::{ArgAction, Parser};

#[derive(Parser, Debug)]
#[command(
    name = "librespeed-cli",
    about = "Test your Internet speed with LibreSpeed",
    version = None,
    disable_version_flag = true
)]
pub struct Cli {
    /// Show the version number and exit
    #[arg(long)]
    pub version: bool,

    /// Force IPv4 only
    // Both may be given; --ipv4 wins, the precedence the Go client applies.
    #[arg(long = "ipv4", short = '4')]
    pub ipv4: bool,

    /// Force IPv6 only
    #[arg(long = "ipv6", short = '6')]
    pub ipv6: bool,

    /// Do not perform download test
    #[arg(long = "no-download")]
    pub no_download: bool,

    /// Do not perform upload test
    #[arg(long = "no-upload")]
    pub no_upload: bool,

    /// Do not use ICMP ping. ICMP doesn't work well under Linux
    /// at this moment, so you might want to disable it
    #[arg(long = "no-icmp")]
    pub no_icmp: bool,

    /// Concurrent HTTP requests being made
    #[arg(long, default_value_t = 3, value_parser = clap::value_parser!(u32).range(1..))]
    pub concurrent: u32,

    /// Display values in bytes instead of bits. Does not affect
    /// the image generated by --share, nor output from --json or --csv
    #[arg(long)]
    pub bytes: bool,

    /// Use 1024 bytes as 1 kilobyte instead of 1000
    #[arg(long)]
    pub mebibytes: bool,

    /// Change distance unit shown in ISP info, use 'mi' for miles,
    /// 'km' for kilometres, 'NM' for nautical miles
    #[arg(long, default_value = "km")]
    pub distance: String,

    /// Generate and provide a URL to the LibreSpeed.org share results
    /// image, not displayed with --csv
    #[arg(long)]
    pub share: bool,

    /// Suppress verbose output, only show basic information
    #[arg(long)]
    pub simple: bool,

    /// Suppress verbose output, only show basic information in CSV
    /// format. Speeds listed in Mbps and not affected by --bytes
    #[arg(long)]
    pub csv: bool,

    /// Single character delimiter to use in CSV output
    #[arg(
        long = "csv-delimiter",
        value_name = "CSV_DELIMITER",
        default_value = ","
    )]
    pub csv_delimiter: String,

    /// Print CSV headers
    #[arg(long = "csv-header")]
    pub csv_header: bool,

    /// Suppress verbose output, only show basic information in JSON
    /// format. Speeds listed in Mbps and not affected by --bytes
    #[arg(long)]
    pub json: bool,

    /// Emit NDJSON progress events on stdout while the test runs, ending
    /// with an event carrying the same report --json prints
    #[arg(long = "json-stream", conflicts_with_all = ["json", "csv"])]
    pub json_stream: bool,

    /// Display a list of LibreSpeed.org servers
    #[arg(long)]
    pub list: bool,

    /// Specify a SERVER ID to test against. Can be supplied
    /// multiple times. Cannot be used with --exclude
    #[arg(long, value_name = "SERVER", action = ArgAction::Append, conflicts_with = "exclude")]
    pub server: Vec<i64>,

    /// EXCLUDE a server from selection. Can be supplied
    /// multiple times. Cannot be used with --server
    #[arg(long, value_name = "EXCLUDE", action = ArgAction::Append)]
    pub exclude: Vec<i64>,

    /// Use an alternative server list from remote JSON file
    #[arg(long = "server-json")]
    pub server_json: Option<String>,

    /// Use an alternative server list from local JSON file,
    /// or read from stdin with "--local-json -"
    #[arg(long = "local-json")]
    pub local_json: Option<String>,

    /// SOURCE IP address to bind to
    #[arg(long, value_name = "SOURCE")]
    pub source: Option<String>,

    /// Network INTERFACE to bind to
    #[arg(long, value_name = "INTERFACE")]
    pub interface: Option<String>,

    /// HTTP TIMEOUT in seconds
    #[arg(long, value_name = "TIMEOUT", default_value_t = 15, value_parser = clap::value_parser!(u64).range(0..))]
    pub timeout: u64,

    /// Upload and download test duration in seconds
    #[arg(long, default_value_t = 15, value_parser = clap::value_parser!(u64).range(1..))]
    pub duration: u64,

    /// Chunks to download from server, chunk size depends on server configuration
    #[arg(long, default_value_t = 100, value_parser = clap::value_parser!(u32).range(1..))]
    pub chunks: u32,

    /// Size of payload being uploaded in KiB
    #[arg(long = "upload-size", default_value_t = 1024, value_parser = clap::value_parser!(u32).range(1..))]
    pub upload_size: u32,

    /// Use HTTPS instead of HTTP when communicating with
    /// LibreSpeed.org operated servers
    // Both may be given; --secure wins, as it does in the Go client.
    #[arg(long)]
    pub secure: bool,

    /// Use HTTP instead of HTTPS when communicating with
    /// LibreSpeed.org operated servers
    #[arg(long)]
    pub insecure: bool,

    /// Use the specified CA certificate PEM bundle file instead
    /// of the system certificate trust store
    #[arg(long = "ca-cert")]
    pub ca_cert: Option<std::path::PathBuf>,

    /// Skip verifying SSL certificate for HTTPS connections (self-signed certs)
    #[arg(long = "skip-cert-verify")]
    pub skip_cert_verify: bool,

    /// Do not pre allocate upload data. Pre allocation is
    /// enabled by default to improve upload performance. To
    /// support systems with insufficient memory, use this
    /// option to avoid out of memory errors
    #[arg(long = "no-pre-allocate")]
    pub no_pre_allocate: bool,

    /// Debug mode (verbose logging)
    #[arg(long, alias = "verbose", hide = true)]
    pub debug: bool,

    /// Load telemetry server settings from a JSON file. This
    /// option overrides --telemetry-level, --telemetry-server,
    /// --telemetry-path, and --telemetry-share. Implies --share
    #[arg(long = "telemetry-json")]
    pub telemetry_json: Option<String>,

    /// Set telemetry data verbosity, available values are:
    /// disabled, basic, full, debug. Implies --share
    #[arg(long = "telemetry-level")]
    pub telemetry_level: Option<String>,

    /// Set the telemetry server base URL. Implies --share
    #[arg(long = "telemetry-server")]
    pub telemetry_server: Option<String>,

    /// Set the telemetry upload path. Implies --share
    #[arg(long = "telemetry-path")]
    pub telemetry_path: Option<String>,

    /// Set the telemetry share link path. Implies --share
    #[arg(long = "telemetry-share")]
    pub telemetry_share: Option<String>,

    /// Send a custom message along with the telemetry results.
    /// Implies --share
    #[arg(long = "telemetry-extra")]
    pub telemetry_extra: Option<String>,

    /// Firewall mark to set on socket
    #[arg(long, default_value_t = 0)]
    pub fwmark: u32,

    /// Allow HTTP/2 when the server offers it. Off by default: HTTP/2 carries
    /// every stream over one TCP connection, so --concurrent would no longer
    /// mean concurrent connections, which is what a speed test measures
    #[arg(long = "http2")]
    pub http2: bool,
}

impl Cli {
    /// True when any output mode that suppresses the interactive UI is active.
    pub fn silent(&self) -> bool {
        self.simple || self.json || self.csv || self.json_stream
    }

    /// The CSV delimiter as a single byte.
    pub fn csv_delimiter_byte(&self) -> anyhow::Result<u8> {
        let bytes = self.csv_delimiter.as_bytes();
        if bytes.len() != 1 {
            anyhow::bail!(
                "--csv-delimiter must be a single character, got {:?}",
                self.csv_delimiter
            );
        }
        Ok(bytes[0])
    }
}
